# Numpy:Introduction

- NumPy is a Open Source Python package. It stands for **Numerical Python**. It is a library consisting of multidimensional array objects and a collection of routines for processing of array.

- NumPy is the fundamental package for scientific computing with Python , having following important functionalities: 
     - A powerful N-dimensional array object
     - A sophisticated (broadcasting) functions
     - Contains tools for integrating C/C++ and Fortran code
     - Have  useful  linear algebra, Fourier transform, and random number capabilities

### Why NuMpy?

- Mathematical and logical operations on **arrays**.

- Efficient storage and manipulation of **numerical arrays** is which is fundamental in  the process of  **data science**.

- NumPy arrays form the core of nearly the entire **ecosystem** of **data science** tools in Python,

In [ ]:
!pip install numpy

In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

# We have lists in Python which serve the purpose of arrays,but their processing is slow.NumPy intends for providing an array object which is upto 50x faster as compared to handed-down Python lists

## In numpy,the array object is called ndarray.
## Arrays are oftentimes used in data science where resources and speed are essential.

In [6]:
# Unlike lists,in memory , NumPy arrays are stored at one continuous place so processes can easily access andmanipulate them.This is called LOCALITY OF REFERENCE

In [7]:
## Arrays are homogeneous (same data type)

In [5]:
## It is a table of elements (typically numbers),all of the similar type, indexed by a tuple of positive integers

In [4]:
## Dimensions are named as axes in Numpy.The number of axes is rank

In [3]:
### NumPy's array class is know as ndarray.Even , it is known by the alias array

In [8]:
a =(1,2,3,4,5)

print(a)

(1, 2, 3, 4, 5)


In [9]:
type(a)

tuple

In [10]:
b= np.array(a)
print(b)

[1 2 3 4 5]


In [11]:
type(b)

numpy.ndarray

In [12]:
b.ndim # in order to find the dimsn

1

In [13]:
b.shape # no.of rows and no.columns

(5,)

In [14]:
b.size # total number of elements present in an array

5

In [15]:
b.dtype ## data type of my array

dtype('int32')

In [16]:
arr = np.array([[4,5,6],[7,8,9]])

print("Array elements are: ",arr)
print("Array is of type: ",type(arr))
print("No.of dimensions: ",arr.ndim)
print("Array shape: ",arr.shape)
print("Array size: ",arr.size)
print("Array stores elements of type: ",arr.dtype)

Array elements are:  [[4 5 6]
 [7 8 9]]
Array is of type:  <class 'numpy.ndarray'>
No.of dimensions:  2
Array shape:  (2, 3)
Array size:  6
Array stores elements of type:  int32


In [17]:
import numpy as arr

a =(1,2,3,4,5)
b =arr.array(a)
print (b)

[1 2 3 4 5]


#### Speed Comaprison numpy vs core python

In [19]:
import time as tm
import numpy as np

size_1 = 10000000

def pure_python_version():
    start_time_pp =  tm.time() ## time of start of code execution
    list1 = range(size_1)
    list2 = range(size_1)
    sum_list=[list1[i]+list2[i] for i in range(len(list1))]
    end_time_pp =  tm.time()
    return end_time_pp - start_time_pp ## end time for execution (difference)

def numpy_version():
    start_time_np = tm.time()
    array1 = np.arange(size_1)
    array2 =  np.arange(size_1)
    sum_array = array1 + array2
    end_time_np = tm.time()
    return end_time_np - start_time_np ## end time for execution (difference)

python_time = pure_python_version()
numpy_time  = numpy_version()

print("pure python version=",python_time)
print("numpy =",numpy_time)

pure python version= 2.360142946243286
numpy = 0.02500128746032715


In [20]:
my_list=[2,3,4,6,7,8]

In [21]:
my_array=np.array(my_list)
my_array

array([2, 3, 4, 6, 7, 8])

In [22]:
array_2 = [[1,2,3],[4,5,6],[7,8,9]]
array_3= np.array(array_2)
array_3
type(array_3)

numpy.ndarray

In [23]:
array_3.shape

(3, 3)

In [24]:
array_3.size

9

In [26]:
array_3.dtype

dtype('int32')

In [27]:
array_3.ndim

2

In [28]:
a = np.array([1, 2, 3,7,5,1], ndmin = 2) 
print (a)
np.ndim(a)

[[1 2 3 7 5 1]]


2

In [29]:
a = np.array([1, 2, 3], dtype = complex) 
print (a)

[1.+0.j 2.+0.j 3.+0.j]


In [30]:
array_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
len(array_3) # total number of rows

3

In [32]:
array_3[2] #Indexing 3rd row

array([7, 8, 9])

In [33]:
array_3[0] 

array([1, 2, 3])

In [34]:
array_3[2,1]

8

In [35]:
array_3[2,0]

7

In [36]:
array_3[:,1] # Acessing Column

array([2, 5, 8])

In [37]:
array_3[:,0] # Acessing Column

array([1, 4, 7])

In [38]:
array_3[2:,:]

array([[7, 8, 9]])

In [39]:
array_3[2:,:1] ## 3rd row onwards until 1st column

array([[7]])

In [40]:
array_3[2:,:2] ## 3rd row onwards until 2nd column

array([[7, 8]])

In [41]:
array_3[1:,:2] ## 3rd row onwards until 2nd column

array([[4, 5],
       [7, 8]])

### Array Atrributes
Numpy Arrays are conveinent and fast as compared to Python Lists.
1.Shape(no of rows & columns)

In [42]:
array_3.shape #Rows*Column

(3, 3)

In [43]:
my_array.ndim #dimension of array

1

In [44]:
array_3.dtype

dtype('int32')

In [45]:
## Array Initilization

In [46]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.arange(1,10,3) #(start,end,space)

array([1, 4, 7])

In [48]:
np.arange(1.8,10.4,3)

array([1.8, 4.8, 7.8])

In [49]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [50]:
np.zeros(9,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [51]:
np.zeros((3,2),dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [52]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [53]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [54]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [55]:
np.linspace(0,4,10) # (start,end,no of values)

array([0.        , 0.44444444, 0.88888889, 1.33333333, 1.77777778,
       2.22222222, 2.66666667, 3.11111111, 3.55555556, 4.        ])

In [56]:
np.linspace(0,2,10) # (start,end,no of values)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [57]:
np.linspace(1.23,4.7,10)

array([1.23      , 1.61555556, 2.00111111, 2.38666667, 2.77222222,
       3.15777778, 3.54333333, 3.92888889, 4.31444444, 4.7       ])

In [58]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [59]:
np.eye(3,4) # Identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [60]:
np.eye(6,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

### Array Initilization with Random numbers
In various applications( like assigning weights in Artificial Neural Networks) arrays need to be initialised randomly.
for this purpose there are various predefined functions in Numpy(reshape and random)

In [62]:
np.random.rand(2)

array([0.96190165, 0.87824332])

In [63]:
np.random.rand(4)

array([0.32310498, 0.27289442, 0.04203539, 0.89868216])

In [64]:
np.random.rand(9)

array([5.75768853e-01, 5.54279127e-01, 9.20517767e-01, 5.58953624e-01,
       4.62388601e-01, 3.72539069e-04, 4.29825172e-01, 6.98138435e-01,
       2.72804412e-01])

In [65]:
np.random.rand(2,2)

array([[0.66244194, 0.40664611],
       [0.57333286, 0.54538099]])

In [66]:
array_3.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [67]:
array_3.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [68]:
arr1 =np.random.rand(9).reshape(3,3)

In [69]:
arr1

array([[0.53568466, 0.83363451, 0.08493262],
       [0.17519579, 0.36964761, 0.3467654 ],
       [0.22121205, 0.68429169, 0.69167521]])

In [70]:
arr1.ndim

2

In [71]:
### Indexing arrays

In [72]:
array_1 = np.arange(1,15)
array_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [73]:
array_1[2]

3

In [74]:
array_1[2:6]

array([3, 4, 5, 6])

In [75]:
array_1[-3]

12

In [76]:
array_1[:-3] # before values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [77]:
array_1[2:6] = 8 # mutable i.e to change the member value of array

In [78]:
array_1

array([ 1,  2,  8,  8,  8,  8,  7,  8,  9, 10, 11, 12, 13, 14])

In [79]:
array_2=[[1,2,3],[4,5,6],[7,8,9]]
array_2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [80]:
np.array(array_2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
np.eye(4,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]])

In [83]:
np.arange(2,2,16)

array([], dtype=int32)

In [85]:
np.arange(2,2)


array([], dtype=int32)

In [86]:
x=[[1,2,3,4],[4,5,6,7],[7,8,9,10],[10,11,12,13]]
x=np.array(x)
x

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [10, 11, 12, 13]])

In [87]:
x.min() ## overrall minimum

1

In [88]:
x.max()

13

In [89]:
x.mean()

7.0

In [90]:
x.min(axis=0) ## minimum value column wise

array([1, 2, 3, 4])

In [91]:
x.max(axis=0) ## minimum value column wise

array([10, 11, 12, 13])

In [92]:
x.max(axis=1) ## minimum value column wise

array([ 4,  7, 10, 13])

In [93]:
x.argmin() ## index of the minimum value 

0

In [94]:
x.argmax() ## index of the minimum value 

15

In [95]:
x.argmin(axis=0) #column wise

array([0, 0, 0, 0], dtype=int64)

In [96]:
x.argmax(axis=1) #column wise

array([3, 3, 3, 3], dtype=int64)

In [97]:
x.reshape(1,16) # 1D to 2D 

array([[ 1,  2,  3,  4,  4,  5,  6,  7,  7,  8,  9, 10, 10, 11, 12, 13]])

In [98]:
x.reshape(2,8) # 1D to 2D 

array([[ 1,  2,  3,  4,  4,  5,  6,  7],
       [ 7,  8,  9, 10, 10, 11, 12, 13]])

In [99]:
x.flatten() #2D to 1D

array([ 1,  2,  3,  4,  4,  5,  6,  7,  7,  8,  9, 10, 10, 11, 12, 13])

In [ ]:
x.transpose()