### math

In [1]:
import numpy as np
A = np.array([ [4, 10, 11], [21, 22, 23], [31, 32, 33] ])
B = np.ones((3,3))
print(A)
print(B)

[[ 4 10 11]
 [21 22 23]
 [31 32 33]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [2]:
print("Adding to arrays: ")
print(A + B)

Adding to arrays: 
[[ 5. 11. 12.]
 [22. 23. 24.]
 [32. 33. 34.]]


In [3]:
print("Substracting Two Arrays")
print(A-B)

Substracting Two Arrays
[[ 3.  9. 10.]
 [20. 21. 22.]
 [30. 31. 32.]]


In [4]:
print("\nMultiplying two arrays: ")
print(A * B)


Multiplying two arrays: 
[[ 4. 10. 11.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [5]:
print("Multiplying one Array with scalar")
print(3*A)

Multiplying one Array with scalar
[[12 30 33]
 [63 66 69]
 [93 96 99]]


In [6]:
print("Matrix Multiplication")
print(np.dot(A,B))

Matrix Multiplication
[[25. 25. 25.]
 [66. 66. 66.]
 [96. 96. 96.]]


In [7]:
np.sqrt(A)

array([[2.        , 3.16227766, 3.31662479],
       [4.58257569, 4.69041576, 4.79583152],
       [5.56776436, 5.65685425, 5.74456265]])

In [8]:
np.exp(A)

array([[5.45981500e+01, 2.20264658e+04, 5.98741417e+04],
       [1.31881573e+09, 3.58491285e+09, 9.74480345e+09],
       [2.90488497e+13, 7.89629602e+13, 2.14643580e+14]])

In [9]:
np.log(A)

array([[1.38629436, 2.30258509, 2.39789527],
       [3.04452244, 3.09104245, 3.13549422],
       [3.4339872 , 3.4657359 , 3.49650756]])

In [10]:
a = np.array([0,30,45,60,90]) 
print(a)
print ('Sine of different angles:' )

[ 0 30 45 60 90]
Sine of different angles:


In [11]:
# Convert to radians by multiplying with pi/180 
print (np.sin(a*np.pi/180) )
print ("\n") 

[0.         0.5        0.70710678 0.8660254  1.        ]




In [12]:
print ('Cosine values for angles in array:')
print (np.cos(a*np.pi/180) )
print ("\n") 

Cosine values for angles in array:
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]




In [13]:
print ('Tangent values for given angles:' )
print (np.tan(a*np.pi/180) )

Tangent values for given angles:
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [14]:
a=np.array([[11.667,23.662],[33.21,45.887]])
print (np.around(a)) 

[[12. 24.]
 [33. 46.]]


In [15]:
print (np.around(a, decimals = 1))

[[11.7 23.7]
 [33.2 45.9]]


In [16]:
print (np.around(a, decimals = 2))

[[11.67 23.66]
 [33.21 45.89]]


In [17]:
A.sum() ## SUM OF ALL THE DATA 

187

In [18]:
B.sum()

9.0

In [19]:
A.sum(axis=0) ## row wise

array([56, 64, 67])

In [20]:
A

array([[ 4, 10, 11],
       [21, 22, 23],
       [31, 32, 33]])

In [21]:
A.sum(axis=1) ## row wise

array([25, 66, 96])

In [22]:
A.mean()

20.77777777777778

In [23]:
A.mean(axis=0)

array([18.66666667, 21.33333333, 22.33333333])

In [24]:
A.mean(axis=1)

array([ 8.33333333, 22.        , 32.        ])

In [25]:
np.std(A)

9.88576729757121

In [26]:
np.std(A,axis=0)

array([11.14550233,  8.99382504,  8.99382504])

In [27]:
np.std(A,axis=1)

array([3.09120617, 0.81649658, 0.81649658])

In [28]:
np.median(A)

22.0

In [29]:
np.mod(A,23)

array([[ 4, 10, 11],
       [21, 22,  0],
       [ 8,  9, 10]], dtype=int32)

In [30]:
A

array([[ 4, 10, 11],
       [21, 22, 23],
       [31, 32, 33]])

In [31]:
np.var(A)    #Variance

97.72839506172839

In [32]:
## Binary Universal Functions

In [33]:
A=[[1,2,3],[3,4,5]]
B=[[3,3,4],[1,2,0]]
a=np.array(A)
b=np.array(B)
np.greater_equal(a,b)

array([[False, False, False],
       [ True,  True,  True]])

In [34]:
np.less(a,b)

array([[ True,  True,  True],
       [False, False, False]])

In [35]:
np.less(b,a)

array([[False, False, False],
       [ True,  True,  True]])

In [36]:
## Subsetting array

In [37]:
subset1 = a[:,0] = 1  ## sub set element before postion 0 to value 1

In [38]:
subset1 = a[:,0]

In [39]:
subset1

array([1, 1])

In [40]:
### Concatenating Arrays

In [41]:
np.concatenate([a,b],axis=1)

array([[1, 2, 3, 3, 3, 4],
       [1, 4, 5, 1, 2, 0]])

In [42]:
np.concatenate([a,b],axis=0)

array([[1, 2, 3],
       [1, 4, 5],
       [3, 3, 4],
       [1, 2, 0]])

In [43]:
a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 
print (c)

[ 10  40  90 160]


In [44]:
np.ndim(b)

1

In [45]:
## Array with different shapes

In [46]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([0.0,1.0,2.0])  
   
print ('First array:\n',a )
print ('Second array:\n',b )
print ("\n")   
print ('First Array + Second Array=\n',a+b)

First array:
 [[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]
Second array:
 [0. 1. 2.]


First Array + Second Array=
 [[ 0.  1.  2.]
 [10. 11. 12.]
 [20. 21. 22.]
 [30. 31. 32.]]


In [47]:
### file input output

In [48]:
a = np.array([11,2,30,4,5,13]) 
np.save('dar',a)

In [49]:
# To reconstruct array from demofile.npy, use load() function.
b = np.load('dar.npy') 
print (b)

[11  2 30  4  5 13]


In [50]:
np.savetxt('dar.txt',a) 
b = np.loadtxt('dar.txt') 
print (b)

[11.  2. 30.  4.  5. 13.]


In [52]:
np.random.randint(2,10,(3,4))

array([[3, 7, 6, 5],
       [4, 3, 9, 3],
       [8, 4, 9, 8]])

In [53]:
np.random.randint(2,50, (2,3,4) )

array([[[43, 21, 14, 21],
        [ 8, 20, 31,  5],
        [37, 38, 39, 23]],

       [[33, 25,  9, 49],
        [31,  9,  7, 24],
        [45,  7, 44, 26]]])

In [54]:
np.random.rand(5,4)

array([[0.5174109 , 0.76446472, 0.1839055 , 0.18352079],
       [0.68737349, 0.64505547, 0.00512664, 0.03687551],
       [0.2230744 , 0.08067758, 0.45682491, 0.94951142],
       [0.10419806, 0.46273585, 0.95176901, 0.78123836],
       [0.88962887, 0.75178343, 0.33248873, 0.90742924]])

In [55]:
a =np.random.randn(4,4)

In [56]:
a

array([[ 1.37927904, -1.26046118, -1.16990724, -0.98621861],
       [ 0.10560889, -0.33342358,  0.53418647,  0.19960345],
       [ 1.70502014,  2.16328577,  0.58264277, -0.44181381],
       [ 0.52976015,  0.61951978, -1.79845096,  0.46516975]])

In [57]:
a.reshape(2,8)

array([[ 1.37927904, -1.26046118, -1.16990724, -0.98621861,  0.10560889,
        -0.33342358,  0.53418647,  0.19960345],
       [ 1.70502014,  2.16328577,  0.58264277, -0.44181381,  0.52976015,
         0.61951978, -1.79845096,  0.46516975]])

In [58]:
a.reshape(1, 16)

array([[ 1.37927904, -1.26046118, -1.16990724, -0.98621861,  0.10560889,
        -0.33342358,  0.53418647,  0.19960345,  1.70502014,  2.16328577,
         0.58264277, -0.44181381,  0.52976015,  0.61951978, -1.79845096,
         0.46516975]])

In [59]:
a.reshape(1,1,1,1,1,1,1,2,2,4)

array([[[[[[[[[[ 1.37927904, -1.26046118, -1.16990724,
                -0.98621861],
               [ 0.10560889, -0.33342358,  0.53418647,
                 0.19960345]],

              [[ 1.70502014,  2.16328577,  0.58264277,
                -0.44181381],
               [ 0.52976015,  0.61951978, -1.79845096,
                 0.46516975]]]]]]]]]])

In [60]:
b =a.reshape(1,1,1,1,1,1,1,2,2,4)

In [62]:
b.ndim

10

In [63]:
a5 = np.random.randint(2,90 , (6,5))

In [64]:
a5

array([[24, 59, 46, 51, 25],
       [79,  2, 20, 87, 21],
       [87, 78,  5, 25, 25],
       [56, 24, 34, 44, 79],
       [64, 27, 88, 78, 60],
       [46, 13, 72, 51, 61]])

In [65]:
a5[a5>40]

array([59, 46, 51, 79, 87, 87, 78, 56, 44, 79, 64, 88, 78, 60, 46, 72, 51,
       61])

In [66]:
a6 = np.random.randint(0,3 , (3,3))

In [67]:
a7 = np.random.randint(0,3 , (3,3))

In [68]:
a6*a7

array([[0, 2, 1],
       [0, 0, 4],
       [2, 0, 4]])

In [69]:
a6@a7

array([[3, 0, 6],
       [2, 0, 4],
       [5, 2, 8]])

In [70]:
a6

array([[0, 2, 1],
       [0, 0, 2],
       [2, 1, 2]])

In [71]:
a7

array([[1, 1, 1],
       [1, 0, 2],
       [1, 0, 2]])

In [72]:
a6+100

array([[100, 102, 101],
       [100, 100, 102],
       [102, 101, 102]])

In [73]:
a6**3

array([[0, 8, 1],
       [0, 0, 8],
       [8, 1, 8]], dtype=int32)

In [74]:
import pandas as pd

In [87]:
pd.read_excel("C:\\Users\\amitm\\Downloads\\Agent_Login_Report (4).xls")

ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 2.0.1 for xls Excel support Use pip or conda to install xlrd.